import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    cart: [],
    total: 0,
    qty: 0,
    products: [
      {
        id: 1,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Graphite",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProGraphite.eb49cd62.jpg",
        price: 999,
      },
      {
        id: 2,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Silver",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProSilver.a28ba0fd.jpg",
        price: 999,
      },
      {
        id: 3,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Gold",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProGold.aa8ea08f.jpg",
        price: 999,
      },
      {
        id: 4,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Pacific Blue",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProPacificBlue.3560edf5.jpg",
        price: 999,
      },
      {
        id: 5,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Graphite",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProGraphite.eb49cd62.jpg",
        price: 1199.0,
      },
      {
        id: 6,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Silver",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProSilver.a28ba0fd.jpg",
        price: 1199,
      },
      {
        id: 7,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Gold",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProGold.aa8ea08f.jpg",
        price: 1199,
      },
      {
        id: 8,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Pacific Blue",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProPacificBlue.3560edf5.jpg",
        price: 1199,
      },
      {
        id: 9,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Graphite",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProGraphite.eb49cd62.jpg",
        price: 1399,
      },
      {
        id: 10,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProSilver.a28ba0fd.jpg",
        price: 1399,
      },
      {
        id: 11,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Gold",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProGold.aa8ea08f.jpg",
        price: 1399,
      },
      {
        id: 12,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone 12 Pro",
        color: "Pacific Blue",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhone12ProPacificBlue.3560edf5.jpg",
        price: 1399,
      },
      {
        id: 13,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "White",
        capacity: "64 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSEWhite.b06067b3.jpg",
        price: 399,
      },
      {
        id: 14,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "White",
        capacity: "64 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSEWhite.b06067b3.jpg",
        price: 399,
      },
      {
        id: 15,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "Red",
        capacity: "64 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSERed.229e99ad.jpg",
        price: 399,
      },
      {
        id: 14,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "White",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSEWhite.b06067b3.jpg",
        price: 499,
      },
      {
        id: 15,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "White",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSEWhite.b06067b3.jpg",
        price: 499,
      },
      {
        id: 16,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "Red",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSERed.229e99ad.jpg",
        price: 499,
      },
      {
        id: 17,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "White",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSEWhite.b06067b3.jpg",
        price: 599,
      },
      {
        id: 18,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "White",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSEWhite.b06067b3.jpg",
        price: 599,
      },
      {
        id: 19,
        type: "Smartphone",
        brand: "Apple",
        model: "iPhone SE",
        color: "Red",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPhoneSERed.229e99ad.jpg",
        price: 599,
      },
      {
        id: 20,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Space Gray",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1299,
      },
      {
        id: 21,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Silver",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1299,
      },
      {
        id: 22,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Space Gray",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1499,
      },
      {
        id: 23,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Silver",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1499,
      },
      {
        id: 24,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Space Gray",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1599,
      },
      {
        id: 25,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1599,
      },
      {
        id: 26,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Space Gray",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1699,
      },
      {
        id: 27,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Silver",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1699,
      },
      {
        id: 28,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Space Gray",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 29,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi",
        color: "Silver",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1799,
      },
      {
        id: 30,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Space Gray",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1546,
      },
      {
        id: 31,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Silver",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1546,
      },
      {
        id: 32,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Space Gray",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1599,
      },
      {
        id: 33,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Silver",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1599,
      },
      {
        id: 34,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Space Gray",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1699,
      },
      {
        id: 35,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1699,
      },
      {
        id: 36,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Space Gray",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 37,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1799,
      },
      {
        id: 38,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Space Gray",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1899,
      },
      {
        id: 39,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Silver",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1899,
      },
      {
        id: 40,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Space Gray",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1999,
      },
      {
        id: 41,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi",
        color: "Silver",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1999,
      },
      {
        id: 42,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 43,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 44,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1899,
      },
      {
        id: 45,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1899,
      },
      {
        id: 46,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 47,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 48,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1699,
      },
      {
        id: 49,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1699,
      },
      {
        id: 50,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1799,
      },
      {
        id: 51,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1799,
      },
      {
        id: 52,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1899,
      },
      {
        id: 53,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 11-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1899,
      },
      {
        id: 54,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 1999,
      },
      {
        id: 55,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 1999,
      },
      {
        id: 56,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 2099,
      },
      {
        id: 55,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "256 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 2099,
      },
      {
        id: 56,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 2199,
      },
      {
        id: 57,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "512 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 2199,
      },
      {
        id: 58,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 2299,
      },
      {
        id: 59,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "1 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 2299,
      },
      {
        id: 60,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Space Gray",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSpaceGray.260a1523.jpg",
        price: 2399,
      },
      {
        id: 61,
        type: "Tablet",
        brand: "Apple",
        model: "iPad Pro 12.9-inch display Wifi + Cellular",
        color: "Silver",
        capacity: "2 TB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/iPadProSilver.14f40de9.jpg",
        price: 2399,
      },
      {
        id: 62,
        type: "Smartphone",
        brand: "Samsung",
        model: "S21 5G",
        color: "Phantom Grey",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/S21PhantomGrey.80353423.jpg",
        price: 799,
      },
      {
        id: 63,
        type: "Smartphone",
        brand: "Samsung",
        model: "S21 5G",
        color: "Phantom Pink",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/S21PhantomPink.257b54ed.jpg",
        price: 799,
      },
      {
        id: 64,
        type: "Smartphone",
        brand: "Samsung",
        model: "S21 5G",
        color: "Phantom Violet",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/S21PhantomViolet.3df3d7e4.jpg",
        price: 799,
      },
      {
        id: 65,
        type: "Smartphone",
        brand: "Samsung",
        model: "S21 5G",
        color: "Phantom White",
        capacity: "128 GB",
        imgSrc: "https://shopping-cart-demo-sith.netlify.app/img/S21PhantomWhite.72f4d7e2.jpg",
        price: 799,
      },
    ],
  },
  getters:{
      products(state) {
        return state.products;
      },
      totalSum(state) {
        return state.total;
      },
      quantity(state) {
        return state.qty;
      },
      cart(state) {
        return state.cart;
      }
  },

  mutations: {
    addProductToCart(state, payload) {
      const productData = payload;
      const productInCartIndex = state.cart.findIndex(
        (ci) => ci.id === productData.id
      );
      if (productInCartIndex >= 0) {
        state.cart[productInCartIndex].qty++;
      } else {
        const newItem = {
          id: productData.id,
          type: productData.type,
          brand: productData.brand,
          model: productData.model,
          color: productData.color,
          capacity: productData.capacity,
          imgSrc: productData.imgSrc,
          price: productData.price,
          qty: 1,
        };
        state.cart.push(newItem);
      }
      state.qty++;
      state.total += productData.price;
    },
    removeProductFromCart(state, payload) {
      const prodId = payload.id;
      const productInCartIndex = state.cart.findIndex(
        (cartItem) => cartItem.id === prodId
      );
      const prodData = state.cart[productInCartIndex];
      state.cart.splice(productInCartIndex, 1);
      state.qty -= prodData.qty;
      state.total -= prodData.price * prodData.qty;
    }
  },
  actions: {
  },
  modules: {
  }
})
